name: Docker image creation

on:
  push:
    branches:
      - master
      
env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: lrydzkowski/api-2
  AZURE_WEBAPP_NAME: test2-api-2
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
  create-image:
    runs-on: ubuntu-latest

    needs: build
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Sign in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build an application docker image
        id: docker_app_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Api2.WebApi/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ github.run_id }}
          
  deploy:
    runs-on: ubuntu-latest
    
    needs: create-image
    
    permissions:
      packages: read
      
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest
